AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation transform resources
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Common parameters
      Parameters:
      - NotificationTopic
      - TimeoutInMinutes
Parameters:
  NotificationTopic:
    Description: Specify optional SNS topic for initial CloudFormation event notifications.
    Type: String
    Default: ''
  TimeoutInMinutes:
    Description: Specify optional timeout in minutes for stack creation.
    Type: Number
    Default: 60
Conditions:
  HasNotifySNS:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: NotificationTopic
Resources:
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/0b4dd3f0-d8c4-11e9-a0de-0f102a395e3c/85f1c7e6e1fe5b1e8f03b2bd6c104adf.template
      Parameters:
        NameTag:
          Fn::Sub: ${AWS::StackName}
      NotificationARNs:
      - Fn::If:
        - HasNotifySNS
        - Ref: NotificationTopic
        - Ref: AWS::NoValue
      TimeoutInMinutes:
        Ref: TimeoutInMinutes
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${AWS::StackName}
  UUID4:
    Type: AWS::CloudFormation::Transform
    Properties:
      Name:
        Fn::Sub: ${AWS::AccountId}::UUID4
      Description: Generates UUID4
      RoutingTable:
        '*': latest
      Versions:
      - VersionName: latest
        Description: latest UUID4 generator
        FunctionName:
          Fn::Sub: ${LambdaStack.Outputs.CustomResourceLambdaArn}
      ExecutionPolicy:
        Version: 2012-10-17
        Id: AllowOtherAccountPolicy
        Statement:
        - Sid: AllowExecution
          Effect: Allow
          Principal:
            AWS:
              Fn::Sub: ${AWS::AccountId}
          Action: cloudformation:CreateChangeSet
          Resource:
            Fn::Sub: arn:*:cloudformation:${AWS::Region}:${AWS::AccountId}:transform/UUID4
  CurrentTimestamp:
    Type: AWS::CloudFormation::Transform
    Properties:
      Name:
        Fn::Sub: ${AWS::AccountId}::UTCTIME
      Description: Generates time stamp in seconds since epoch
      RoutingTable:
        '*': latest
      Versions:
      - VersionName: latest
        Description: latest UTCTIME generator
        FunctionName:
          Fn::Sub: ${LambdaStack.Outputs.CustomResourceLambdaArn}
      ExecutionPolicy:
        Version: 2012-10-17
        Id: AllowOtherAccountPolicy
        Statement:
        - Sid: AllowExecution
          Effect: Allow
          Principal:
            AWS:
              Fn::Sub: ${AWS::AccountId}
          Action: cloudformation:CreateChangeSet
          Resource:
            Fn::Sub: arn:*:cloudformation:${AWS::Region}:${AWS::AccountId}:transform/UTCTIME
Outputs:
  StackName:
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: StackName-${AWS::StackName}
